### 전체 메뉴 조회
GET http://localhost:8080/menus

### 단일 메뉴 조회
GET http://localhost:8080/menus/22

### 신규 메뉴 추가
POST http://localhost:8080/menus
Content-Type: application/json

{
  "menuCode": 0,
  "menuName": "test",
  "menuPrice": "1000",
  "categoryCode": "4",
  "orderableStatus": "Y"
}

### 메뉴 수정
PUT http://localhost:8080/menus
Content-Type: application/json

{
  "menuCode": 22,
  "menuName": "",
  "menuPrice": 0,
  "categoryCode": 0,
  "orderableStatus": ""
}

### 메뉴 삭제
DELETE http://localhost:8080/menus/23